- Dockerfile
- root/etc/cont-init.d/30-config
- root/etc/services.d/healthchecks/run
> initial tidying of dockerfile and size reductions

- root/defaults/local_settings.py
- root/etc/cont-init.d/30-config
> set array and add test no sed yet

- Dockerfile
- root/etc/cont-init.d/30-config
> using array for variables

- Dockerfile
> build docker image with latest release of the code

- root/etc/cont-init.d/30-config
only symlink files necessary for customization
> Logo symlinks

- Dockerfile.aarch64
- Dockerfile.armhf
To resolve missing deps in arm variants.
> adding deps to arm variants #13

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
> add pip install for mysqlclient

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
Need the sys libs for this to work: 
https://github.com/linuxserver/docker-healthchecks/issues/15
> #15 adding mysql libs

- root/etc/cont-init.d/30-config
> DEBUG mode always enabled

- README.md
- readme-vars.yml
- root/etc/cont-init.d/30-config
We welcome all PR’s though this doesn’t guarantee it will be accepted.
Allow to create superuser
Allow to create superuser
code,build,run,test
none
> Allow to create superuser

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/etc/cont-init.d/30-config
Ref PRs: 
https://github.com/linuxserver/docker-healthchecks/pull/29
https://github.com/linuxserver/docker-healthchecks/pull/28
Ref issues:
https://github.com/linuxserver/docker-healthchecks/issues/27
https://github.com/linuxserver/docker-healthchecks/issues/22
We let those PRs sit too long they were tough to merge so here is a fresh one.
> CSRF fix and adding postgres client pip package

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- jenkins-vars.yml
- readme-vars.yml
This PR is part of a larger rebase effort and is being tracked on an internal sheet
> rebasing to alpine 3.11

- Jenkinsfile
- jenkins-vars.yml
> Turn back on web cia

- root/etc/cont-init.d/30-config
We welcome all PR’s though this doesn’t guarantee it will be accepted.
> add config value for specifying ping endpoint

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
fix: missing library for mysql/mariadb integration
> [Bug] Missing MySQL libraries #37

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
Since [v1.18.0](https://github.com/healthchecks/healthchecks/releases/tag/v1.18.0) builds have been failing due to a failure installing the `cryptography` dependency:
* https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-healthchecks/job/master/239/
* https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-healthchecks/job/master/240/
The recommendation for the library suggests the following packages are required for an [Alpine](https://cryptography.io/en/latest/installation.html#alpine) based installation.
So I have …
> Fix v1.18.0 build

- readme-vars.yml
We welcome all PR’s though this doesn’t guarantee it will be accepted.
It was not apparent that the port should also have been set up.
Since the example Docker command and compose file use
the port 8000, it would be nice to have this mentioned in the
SITE_ROOT description.
Proper configuration of the service.
Tested locally.
I had to dig into the official docs to find out about this
https://github.com/healthchecks/healthchecks#configuration
> Mention port in SITE_ROOT env var

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
Rebase to 3.14, remove unneeded build packages.
Tested builds locally with existing install.
> Rebase to Alpine 3.14

- readme-vars.yml
- root/etc/cont-init.d/30-config
Remove img copy, add SITE_LOGO_URL. Upstream no longer supports custom image overwrites and instead provides a SITE_LOGO_URL with which to provide a custom logo. See https://github.com/healthchecks/healthchecks/commit/2382bf6722dcb00d0d4ce1bc57b07cf9efaed154
Closes #71
Built and tested locally.
> Remove img copy, add SITE_LOGO_URL

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- root/etc/cont-init.d/30-config
> overlayfs tmp location workaround

- readme-vars.yml
- root/defaults/uwsgi.ini
Added `sendreports` management command as uWSGI daemon in order to fix issues with [Email Report feature](https://healthchecks.io/docs/configuring_notifications/#:~:text=Weekly%20and%20Monthly%20Reports). A healthchecks.io developer [recently confirmed](https://github.com/healthchecks/healthchecks/issues/706#issuecomment-1251856414) the command is not being started properly by this Docker image. Proper usage of this command [can be seen](https://github.com/healthchecks/healthchecks/blob/master/docker/uwsgi.ini#L17) in the official …
> Fix sending of Email Reports. Closes #92

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- readme-vars.yml
> Add curl-dev to fix broken pip builds, upgrade pip.

- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- Jenkinsfile
- README.md
- jenkins-vars.yml
- readme-vars.yml
- root/defaults/uwsgi.ini
- root/etc/s6-overlay/s6-rc.d/init-healthchecks-config/run
> Process statics at build time, fix migrations

- .github/workflows/call_invalid_helper.yml
- Dockerfile
- Dockerfile.aarch64
- Dockerfile.armhf
- README.md
- readme-vars.yml
- root/defaults/uwsgi.ini
- root/etc/s6-overlay/s6-rc.d/init-healthchecks-config/run
- root/etc/s6-overlay/s6-rc.d/svc-healthchecks/run
Also closes https://github.com/linuxserver/docker-healthchecks/pull/64 as replacement.
> Rebase to 3.17, add extra pycurl deps

- .github/workflows/call_issue_pr_tracker.yml
- .github/workflows/call_issues_cron.yml
- .github/workflows/package_trigger_scheduler.yml
- .github/workflows/permissions.yml
- Jenkinsfile
- README.md
- readme-vars.yml
> Add readme note about CSRF_TRUSTED_ORIGINS

- root/etc/s6-overlay/s6-rc.d/init-healthchecks-config/run
> Run makemigrations as root, move chown.

- readme-vars.yml
Added missing left double quotation mark for the project_logo value.
> Fix project_logo value

- README.md
- readme-vars.yml
> Update ALLOWED_HOSTS info for 3.9 release
